version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: turnir-app
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://${MYSQL_USER:-crystal_user}:${MYSQL_PASSWORD:-pass}@mysql:3306/${MYSQL_DATABASE:-aukus4}
      IP: 0.0.0.0
      PORT: ${APP_PORT:-8080}
      CLIENT_RESTARTER_INTERVAL_SECONDS: ${CLIENT_RESTARTER_INTERVAL_SECONDS:-180}
      CHANNELS_API_URL: ${CHANNELS_API_URL:-https://api.eventlab.dev/api/users?is_active=1&events=aukus4}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID:-NO_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET:-NO_CLIENT_SECRET}
      KICK_CLIENT_ID: ${KICK_CLIENT_ID:-NO_CLIENT_ID}
      KICK_CLIENT_SECRET: ${KICK_CLIENT_SECRET:-NO_CLIENT_SECRET}
    ports:
      - "${APP_PORT:-8080}:8080"
    networks:
      - turnir-network
    volumes:
      - ./logs:/app/logs

networks:
  turnir-network:
    driver: bridge